SushiLavka/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
]

SushiLavka/coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
    path('list/', views.coupons_list, name='list'),
]

SushiLavka/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('info/', include('info.urls', namespace='info')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

SushiLavka/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('created/', views.created, name='order_created'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
]

SushiLavka/cart/models.py
from django.db import models

# Create your models here.

SushiLavka/cart/forms.py
from django import forms
from shop.models import Product



class CartAddProductForm(forms.Form):
    override = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

SushiLavka/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from coupons.forms import CouponApplyForm
from shop.recommender import Recommender
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        print(product.slug)
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=1,
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'override': True})
    coupon_apply_form = CouponApplyForm()

    r = Recommender()
    cart_products = [item['product'] for item in cart]
    if(cart_products):
        recommended_products = r.suggest_products_for(cart_products, max_results=4)
    else:
        recommended_products = []
    if len(cart_products) > 0:
        last_products = cart_products[-1]
    else:
        last_products = None
    return render(request,'cart/detail.html',{'cart': cart,'coupon_apply_form': coupon_apply_form, 'recommended_products': recommended_products, 'last_products': last_products})

SushiLavka/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  Ваша корзина
{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="mt-5 mb-4">Ваша корзина</h1>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Фото</th>
          <th>Продукт</th>
          <th>Кол-во</th>
          <th>Удалить</th>
          <th>Цена за одну</th>
          <th>Цена</th>
        </tr>
      </thead>
      <tbody>
        {% for item in cart %}
          {% with product=item.product %}
            <tr>
              <td>
                <a href="{{ product.get_absolute_url }}">
                  <img src="{% if product.image %}{{ product.image.url }}
                  {% else %}{% static "img/no_image.png" %}{% endif %}" alt="{{ product.name }}" class="img-thumbnail" style="max-width: 100px; max-height: 100px;">
                </a>
              </td>
              <td>{{ product.name }}</td>
              <td>
                  {{ item.quantity }}
              </td>
              <td>
                <form action="{% url "cart:cart_remove" product.id %}" method="post">
                  <button type="submit" class="btn btn-danger">Удалить</button>
                  {% csrf_token %}
                </form>
              </td>
              <td class="num">{{ item.price }} руб</td>
              <td class="num">{{ item.total_price }} руб</td>
            </tr>
          {% endwith %}
        {% endfor %}
        {% if cart.coupon and cart.coupon.price <= cart.get_total_price%}
          <tr class="subtotal">
            <td>Цена</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price|floatformat:2 }} руб</td>
          </tr>
          <tr>
            <td>
              "{{ cart.coupon.code }}" Промокод
              ({{ cart.coupon.discount }}% вкл)
            </td>
            <td colspan="4"></td>
            <td class="num neg">
              - {{ cart.get_discount|floatformat:2 }} руб
            </td>
          </tr>
        {% endif %}
        <tr class="total">
          <td>Всего</td>
          <td colspan="4"></td>
          <td class="num">
            {{ cart.get_total_price_after_discount|floatformat:2 }} руб
          </td>
        </tr>
      </tbody>
    </table>

    <div class="mt-4">
      <p>Промокод:</p>
      <form action="{% url "coupons:apply" %}" method="post">
        {{ coupon_apply_form }}
        <button type="submit" class="btn btn-primary">Принять</button>
        {% csrf_token %}
      </form>
      <p class="text-right">
        {% if last_products == None %}
        <a href="/" class="btn btn-secondary">Продолжить покупку</a>
        {% else %}
          <a href="{{ last_products.category.get_absolute_url }}" class="btn btn-secondary">Продолжить покупку</a>
        {% endif%}
        <a href="{% url "orders:order_create" %}" class="btn btn-success">Оформление заказа</a>
      </p>
    </div>
    {% if recommended_products %}
        <div class="recommendations mt-5">
            <h3 class="font-weight-bold">Также рекомендуем:</h3>
            <div class="row">
                {% for product in recommended_products %}
                <div class="col-md-3 p-5 border" style="position: relative; display: flex; flex-direction: column; align-items: center; text-align: center;">
                    <a href="{{ product.get_absolute_url }}">
                        <img style="height: 130px"src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" class="rounded" style="width: 250px">
                        <a href="{{ product.get_absolute_url }}" style="text-decoration: none;">
                            <span style="color: #4b4748; font-size: 17px; font-weight: 300;">{{ product.name }}</span>
                        </a>
                        <span style="color: red; font-size: 18px; font-weight: 500;">{{ product.price }}руб</span>
                        <div style="margin-top: auto; display: flex">
                            <button type="button" class="btn btn-outline-danger" onclick="addToCart({{ product.id }})"><span style="font-size: 16px; font-weight: 600;">Заказать</span></button>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
  </div>
{% endblock %}