SushiLavka/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
]

SushiLavka/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('info/', include('info.urls', namespace='info')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

SushiLavka/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'


urlpatterns = [
    path('', views.category_list, name='category_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list'),
    path('detail/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

SushiLavka/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    svg = models.TextField()
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list', args=[self.slug])



class Types(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    category = models.ManyToManyField(Category, related_name='types')

    class Meta:
        verbose_name = 'types'
        verbose_name_plural = 'types'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    characteristics = models.TextField(blank=True)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    types = models.ManyToManyField(Types, related_name='type_products')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    price = models.IntegerField()
    weight = models.CharField(max_length=20)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    
    class Meta:
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


    

SushiLavka/shop/views.py
from .recommender import Recommender
from django.shortcuts import render, get_object_or_404
from .models import Category, Types, Product
from cart.forms import CartAddProductForm


def category_list(request, category_slug=None):
    category = None
    categories = Category.objects.all().order_by('id')
    rolls = Product.objects.filter(category=1)[:8]
    sushi = Product.objects.filter(category=2)[:8]
    zakuski = Product.objects.filter(category=3)[:8]
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
    return render(request,'shop/category/category_list.html',{'category': category,'categories': categories,'rolls': rolls, 'sushi': sushi, 'zakuski': zakuski})


def product_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    
    selected_types = request.GET.getlist('types')
    
    products = Product.objects.filter(category=category, available=True)
    for type_id in selected_types:
        products = products.filter(types__id=type_id)

    types = Types.objects.filter(category=category)

    return render(request, 'shop/product/list.html', {
        'products': products,
        'types': types,
        'selected_types': selected_types,
    })


def product_detail(request, id, slug):
    cart_product_form = CartAddProductForm()
    product = get_object_or_404(Product,id=id,slug=slug,available=True)
    types = [type for type in product.types.all()]
    r = Recommender()
    if r.suggest_products_for([product], 4):
        recommended_products = r.suggest_products_for([product], 4)
    else:
        recommended_products = (Product.objects.filter(category=product.category) & Product.objects.exclude(id=product.id))[:4]
    return render(request,'shop/product/detail.html',{'types': types,'product': product,'cart_product_form': cart_product_form,'recommended_products': recommended_products})

SushiLavka/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" class="img-fluid" alt="{{ product.name }}">
        </div>
        <div class="col-md-6">
            <h1 class="mt-3">{{ product.name }}</h1>
            <span class="text-muted font-weight-light">{{ product.art }}</span>
            <h2 class="mt-3">
                <a href="{{ product.category.get_absolute_url }}" class="text-decoration-none text-dark">{{ product.category }}</a>
            </h2>
            <span class="text-danger font-weight-bold h5">{{ product.price }} руб</span>
            <form action="{% url "cart:cart_add" product.id %}" method="post" class="mt-4">
                {{ cart_product_form }}
                {% csrf_token %}
                <button type="submit" value="Add to cart" class="btn btn-outline-secondary btn-lg">Заказать</button>
            </form>
            <p>
                {% for t in types %}
                    <span class="badge">{{ t }},</span>
                {% endfor %}
            </p>
            <b>Энергетическая ценность на 100г. продукта</b>
            <p>{{ product.characteristics|linebreaksbr }}</p>
            <p><em>Вес: {{ product.weight }}</em></p>
        </div>
    </div>

    {% if recommended_products %}
        <div class="recommendations mt-5">
            <h3 class="font-weight-bold">Также рекомендуем:</h3>
            <div class="row">
                {% for product in recommended_products %}
                <div class="col-md-3 p-5 border" style="position: relative; display: flex; flex-direction: column; align-items: center; text-align: center;">
                    <a href="{{ product.get_absolute_url }}">
                        <img style="height: 130px"src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" class="rounded" style="width: 250px">
                        <a href="{{ product.get_absolute_url }}" style="text-decoration: none;">
                            <span style="color: #4b4748; font-size: 17px; font-weight: 300;">{{ product.name }}</span>
                        </a>
                        <span style="color: red; font-size: 18px; font-weight: 500;">{{ product.price }}руб</span>
                        <div style="margin-top: auto; display: flex">
                            <button type="button" class="btn btn-outline-danger" onclick="addToCart({{ product.id }})"><span style="font-size: 16px; font-weight: 600;">Заказать</span></button>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock %}

SushiLavka/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block content %}
    <form method="GET">
      <button type="button" class="btn btn-outline-warning left" onclick="toggleMenu()">
          <span style="font-size: 20px; font-weight: 500;">Подбор по ингредиентам</span>
      </button>
      <br>
      <div class="ingredient-dropdown" id="ingredientDropdown">
          <div id="ingredientMenu" class="ingredient-menu">
              <div class="row" style="margin: 0; display: flex; padding: 10px;">
                  {% for type in types %}
                      <div class="col-6 col-md-4 col-lg-3 mb-2" style="text-align: left">
                          <label class="form-check-label">
                              <input type="checkbox" class="form-check-input" name="types" value="{{ type.id }}">
                              {{ type.name }}
                          </label>
                      </div>
                  {% endfor %}
              </div>
              <button type="submit" class="btn btn-primary">Подобрать</button>
          </div>
      </div>
  </form>
    <div class="row row-cols-3">
            {% if products|length < 1 %}
            <span style="color: #4b4748; font-size: 25px; font-weight: 600;">Ничего нет(</span>
                  
            {%endif%}

            {% for product in products %}
            <div class="col-md-3 p-5 border" style="position: relative; display: flex; flex-direction: column; align-items: center; text-align: center;">
              <a href="{{ product.get_absolute_url }}">
                  <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" class="rounded" style="width: 250px">
                  <a href="{{ product.get_absolute_url }}" style="text-decoration: none;">
                      <span style="color: #4b4748; font-size: 22px; font-weight: 300;">{{ product.name }}</span>
                  </a>
                  <span style="color: red; font-size: 20px; font-weight: 500;">{{ product.price }}руб</span>
                  <span style="color: gray; font-size: 15px; font-weight: 100;">{{ product.weight}}</span>
                  <span style="text-align: left; color: #4b4748; font-size: 15px; font-weight: 400;">
                  {% for product_type in product.types.all %}
                      {{ product_type.name }}{% if not forloop.last %}, {% endif %}
                      {% endfor %}
                  </span>
                  <br>
                  <div style="margin-top: auto; display: flex">
                      <button type="button" class="btn btn-outline-danger" onclick="addToCart({{ product.id }})"><span style="font-size: 18px; font-weight: 600;">Заказать</span></button>
                  </div>
              </a>
          </div>
          {% endfor %}
    </div>    
{% endblock %}

{% block js %}
<script>
  const csrftoken = Cookies.get('csrftoken');
  function addToCart(productId) {

    fetch('/cart/add/'+ productId + '/', {
        method: 'POST',
        headers: {'X-CSRFToken': csrftoken},
    })
    .then(data => {
      window.location.href = "{% url 'cart:cart_detail' %}";
    });
  }

  function toggleMenu() {
    const menu = document.getElementById('ingredientMenu');
    const dropdown = document.getElementById('ingredientDropdown');
    const isMenuVisible = menu.style.display === 'block';

    if (isMenuVisible) {
        menu.style.display = 'none';
        dropdown.style.marginBottom = '0';
    } else {
        menu.style.display = 'block';
        dropdown.style.marginBottom = `${menu.clientHeight}px`;
    }
}
</script>
{% endblock %}