SushiLavka/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
]

SushiLavka/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('info/', include('info.urls', namespace='info')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

SushiLavka/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('created/', views.created, name='order_created'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
]

SushiLavka/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'


urlpatterns = [
    path('', views.category_list, name='category_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list'),
    path('detail/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

SushiLavka/orders/models.py
from django.db import models
from shop.models import Product
from decimal import Decimal
from django.core.validators import MinValueValidator, MaxValueValidator
from coupons.models import Coupon
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField


class Order(models.Model):
    first_name = models.CharField(null=False, blank=False, max_length=50)
    phone = PhoneNumberField(null=False, blank=False)
    address = models.CharField(max_length=250, null=True, blank=True)
    delivery = models.BooleanField(default=False)
    comment = models.TextField(null=True, blank=True)
    delivery_date = models.DateTimeField(max_length=25)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    uuid = models.CharField(max_length=50, null=True, blank=True)
    coupon = models.ForeignKey(Coupon, related_name='orders', null=True, blank=True, on_delete=models.SET_NULL)
    discount = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])


    class Meta:
        ordering = ['-created']
        indexes = [models.Index(fields=['-created']),]

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        total_cost = self.get_total_cost_before_discount()
        return total_cost - self.get_discount()

    def get_total_cost_before_discount(self):
        return sum(item.get_cost() for item in self.items.all())

    def get_discount(self):
        total_cost = self.get_total_cost_before_discount()

        if self.discount:
            return total_cost * (self.discount / Decimal(100))
        return Decimal(0)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return str(self.id)
  
    def get_cost(self):
        return self.price * self.quantity

SushiLavka/orders/forms.py
from django import forms
from .models import Order
from phonenumber_field.formfields import PhoneNumberField

PAYMENT_CHOICES = [
    ('cash', 'Наличными'),
    ('card', 'Картой'),
]

class PaymentForm(forms.Form):
    payment_method = forms.ChoiceField(
        label='Выберите способ оплаты',
        choices=PAYMENT_CHOICES,
        widget=forms.RadioSelect,  
    )


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'phone', 'delivery', 'address', 'comment', 'delivery_date']

    first_name = forms.CharField(max_length=50, label="Имя")
    phone = PhoneNumberField(label="Номер телефона")
    delivery = forms.BooleanField(required=False, label="Доставка")
    address = forms.CharField(max_length=250, required=False, label="Адреc")
    comment = forms.CharField(max_length=250, required=False, label="Комментарий")
    delivery_date = forms.DateTimeField(required=True, label="Дата доставки")

SushiLavka/orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.admin.views.decorators import staff_member_required
from .models import OrderItem, Order
from .forms import OrderCreateForm, PaymentForm
from cart.cart import Cart
from .tasks import order_created
from django.urls import reverse
from shop.recommender import Recommender


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        payment_methods = PaymentForm(request.POST) 
        if form.is_valid() and payment_methods.is_valid():  
            payment_method = payment_methods.cleaned_data['payment_method']
            order = form.save(commit=False)
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.discount
            order.save()
            r = Recommender()
            recommender = []
            for item in cart:
                recommender.append(item['product'])
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])
            r.products_bought(recommender)
            cart.clear()
            order_created.delay(order.id)
            request.session['order_id'] = order.id
            if payment_method == 'cash':
                return redirect(reverse('orders:order_created'))
            return redirect(reverse('payment:process'))
    else:
        form = OrderCreateForm()
        payment_methods = PaymentForm() 

    return render(request, 'orders/order/create.html', {'cart': cart, 'form': form, 'payment_methods': payment_methods})


def created(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'orders/order/created.html', {'order': order})


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'admin/orders/order/detail.html', {'order': order})

SushiLavka/orders/templates/orders/order/create.html
{% extends "shop/base.html" %}

{% block title %}
  Оформление заказа
{% endblock %}

{% block content %}
  <div class="container">
    <div class="py-5 text-center">
      <h1 class="mb-3">Оформление заказа</h1>
    </div>

    <div class="row">
      <div class="col-md-6 order-md-1">
        <h4 class="mb-3">Ваш заказ</h4>
        <ul class="list-group mb-3">
          {% for item in cart %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{ item.product.name }}</h6>
                <small class="text-muted">{{ item.quantity }} x {{ item.product.price }} руб</small>
              </div>
              <span class="text-muted">{{ item.total_price|floatformat:2 }} руб</span>
            </li>
          {% endfor %}
          {% if cart.coupon and cart.coupon.price <= cart.get_total_price%}
            <li class="list-group-item d-flex justify-content-between">
              <span>Промокод "{{ cart.coupon.code }}" ({{ cart.coupon.discount }}% скидка)</span>
              <span class="neg">- {{ cart.get_discount|floatformat:2 }} руб</span>
            </li>
          {% endif %}
          <li class="list-group-item d-flex justify-content-between">
            <span>Итого</span>
            <strong>{{ cart.get_total_price_after_discount|floatformat:2 }} руб</strong>
          </li>
        </ul>
      </div>
      <div class="col-md-6 order-md-2">
        <h4 class="mb-3">Данные для заказа</h4>
        <form method="post" class="order-form">
          {% csrf_token %}
          <div class="form-group">
            {{ form.first_name.label_tag }}
            <input type="text" class="form-control" name="{{ form.first_name.name }}" placeholder="Ваше имя" required>
          </div>
          <div class="form-group">
            {{ form.phone.label_tag }}
            <input type="text" class="form-control" name="{{ form.phone.name }}" placeholder="Номер телефона" required>
          </div>
          <div class="form-group">
            {{ form.comment.label_tag }}
            <textarea class="form-control" rows="3" name="{{ form.comment.name }}"></textarea>
          </div>
          <div class="form-group">
            {{ form.delivery.label_tag }}
            {{ form.delivery }}
          </div>
          <div id="address-group" class="form-group" style="display: none;">
            {{ form.address.label_tag }}
            <input type="text" class="form-control" name="{{ form.address.name }}" placeholder="Адрес">
          </div>
          <div class="form-group">
            <label for="{{ form.delivery_date.id_for_label }}">{{ form.delivery_date.label }}</label>
            <input type="datetime-local" class="form-control" name="{{ form.delivery_date.name }}" id="{{ form.delivery_date.id_for_label }}" required 
                   min="{{ now|date:'Y-m-d' }}T09:00" max="{{ now|date:'Y-m-d' }}T21:00" step="600">
            </div>
            <div class="form-group">
              {{ payment_methods.payment_method.label_tag }}
              <ul>
                {% for radio in payment_methods.payment_method %}
                  <li>
                    {{ radio }}
                  </li>
                {% endfor %}
              </ul>
              </div>
          <hr class="mb-4">
          <button class="btn btn-primary btn-lg btn-block" type="submit">Оформить заказ</button>
        </form>
      </div>
    </div>
  </div>

  <script>
    $(document).ready(function() {
      $('#id_delivery').change(function() {
        if ($(this).is(':checked')) {
          $('#address-group').show();
        } else {
          $('#address-group').hide();
        }
      });

      $('#{{ form.delivery_date.id_for_label }}').on('input', function() {
        var selectedMinute = parseInt($(this).val().split(':')[1]);
        var roundedMinute = Math.floor(selectedMinute / 10) * 10;
        $(this).val($(this).val().split(':')[0] + ':' + roundedMinute);
      });
    });
  </script>
{% endblock %}

SushiLavka/orders/templates/orders/order/created.html
{% extends "shop/base.html" %}

{% block title %}
    Спасибо
{% endblock %}

{% block content %}
    <div class="container">
        <div class="py-5 text-center">
            <h1 class="mb-3">Спасибо</h1>
            <p>Ваш заказ успешно оформлен. Номер вашего заказа: <strong>{{ order.id }}</strong>.</p>
        </div>

        <div class="text-center">
            <p>Вы будете перенаправлены на главную страницу через <span id="countdown">5</span> секунд(ы).</p>
        </div>
    </div>

    <script>
        function countdown() {
            var seconds = 5;
            var countdownElement = document.getElementById('countdown');
            var countdownInterval = setInterval(function() {
                seconds--;
                countdownElement.innerText = seconds;
                if (seconds <= 0) {
                    clearInterval(countdownInterval);
                    window.location.href = "{% url 'shop:category_list' %}";
                }
            }, 1000);
        }
        document.addEventListener('DOMContentLoaded', function() {
            countdown();
        });
    </script>
{% endblock %}