SushiLavka/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
]

SushiLavka/coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
    path('list/', views.coupons_list, name='list'),
]

SushiLavka/info/urls.py
from django.urls import path
from . import views

app_name = 'info'


urlpatterns = [
    path('map/', views.map, name='map'),
    path('info/', views.info, name='info'),
]

SushiLavka/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('info/', include('info.urls', namespace='info')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

SushiLavka/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'


urlpatterns = [
    path('', views.category_list, name='category_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list'),
    path('detail/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

SushiLavka/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    svg = models.TextField()
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list', args=[self.slug])



class Types(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    category = models.ManyToManyField(Category, related_name='types')

    class Meta:
        verbose_name = 'types'
        verbose_name_plural = 'types'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    characteristics = models.TextField(blank=True)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    types = models.ManyToManyField(Types, related_name='type_products')
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    price = models.IntegerField()
    weight = models.CharField(max_length=20)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    
    class Meta:
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


    

SushiLavka/shop/views.py
from .recommender import Recommender
from django.shortcuts import render, get_object_or_404
from .models import Category, Types, Product
from cart.forms import CartAddProductForm


def category_list(request, category_slug=None):
    category = None
    categories = Category.objects.all().order_by('id')
    rolls = Product.objects.filter(category=1)[:8]
    sushi = Product.objects.filter(category=2)[:8]
    zakuski = Product.objects.filter(category=3)[:8]
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
    return render(request,'shop/category/category_list.html',{'category': category,'categories': categories,'rolls': rolls, 'sushi': sushi, 'zakuski': zakuski})


def product_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    
    selected_types = request.GET.getlist('types')
    
    products = Product.objects.filter(category=category, available=True)
    for type_id in selected_types:
        products = products.filter(types__id=type_id)

    types = Types.objects.filter(category=category)

    return render(request, 'shop/product/list.html', {
        'products': products,
        'types': types,
        'selected_types': selected_types,
    })


def product_detail(request, id, slug):
    cart_product_form = CartAddProductForm()
    product = get_object_or_404(Product,id=id,slug=slug,available=True)
    types = [type for type in product.types.all()]
    r = Recommender()
    if r.suggest_products_for([product], 4):
        recommended_products = r.suggest_products_for([product], 4)
    else:
        recommended_products = (Product.objects.filter(category=product.category) & Product.objects.exclude(id=product.id))[:4]
    return render(request,'shop/product/detail.html',{'types': types,'product': product,'cart_product_form': cart_product_form,'recommended_products': recommended_products})

SushiLavka/shop/templates/shop/base.html
{% load static %}
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}СушиЛавка{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </head>
  <body>
    <div style="position: fixed; width: 100%; left: 0; top: 0; height: 20px; z-index: 1000">
        <nav class="navbar navbar-expand-lg navbar-light px-0 border"  style="background-color: white; height: 90px;">
            <a class="navbar-brand" href="/">
                <img src="{% static 'img/logo.png' %}" alt="logo" style="height: 100%;">
            </a>
            <ul class="navbar-nav mx-auto">
                <li class="nav-item mr-5">
                    <a class="nav-link" href="/">
                        <span style="color: gray; font-size: 24px; font-weight: 500;">Меню</span>
                    </a>
                </li>
                <li class="nav-item mr-5">
                    <a class="nav-link" href="{% url 'info:map' %}">
                        <span style="color: gray; font-size: 24px; font-weight: 500;">Контакты</span>
                    </a>
                </li>
                <li class="nav-item mr-5">
                    <a class="navbar-brand" href="/">
                        <span style="color: #4b4748; font-size: 26px; font-weight: 500;">СушиЛавка</span>
                    </a>
                </li>
                <li class="nav-item mr-5">
                    <a class="nav-link" href="{% url 'coupons:list' %}">
                        <span style="color: gray; font-size: 24px; font-weight: 500;">Акции</span>
                    </a>
                </li>
                <li class="nav-item mr-5">
                    <a class="nav-link" href="{%url 'info:info'%}">
                        <span style="color: gray; font-size: 24px; font-weight: 500;">О нас</span>
                    </a>
                </li>
    
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    {% if cart.get_total_price > 0 %}
                    <a class="nav-link" href="{% url "cart:cart_detail" %}">
                        {% endif %}
                        <span style="color: #4b4748; font-size: 18px; font-weight: 400;">Корзина</span>
                        {% with total_items=cart|length %}
                            {% if total_items > 0 %}
                            <span class="badge badge-secondary" style="color: white; font-size: 16px; font-weight: 400;">
                                {{ cart.get_total_price }} руб
                            </span>
                            {% else %}
                            <span class="badge badge-secondary" style="color: white; font-size: 16px; font-weight: 400;">Корзина пуста</span>
                            {% endif %}
                        {% endwith %}
                    </a>
                </li>
            </ul>
        </nav>
      <div class="container-fluid" style="width: 15%; margin-left: 0">
          <div class="row">
              <div class="sidebar-sticky">
                  <ul class="nav flex-column">
                      {% for c in categories %}
                          <div class="d-flex align-items-center">
                              <a class="link" href="{{ c.get_absolute_url }}" style="text-decoration: none">
                                  <div class="border hide" data-category-name="{{ c.name }}">
                                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 40" width="70" height="70"  style="background-color: white">
                                          {{ c.svg | safe }}
                                      </svg>
                                      <div class="category-name">
                                          <span style="color: #4b4748; font-size: 22px; font-weight: 500;">{{ c.name }}</span>
                                      </div>
                                  </div>
                              </a>
                          </div>
                      {% endfor %}
                  </ul>
              </div>
          </div>
      </div>
  </div>
  <div class="container-fluid" style="width: 65%; margin-top: 5%; z-index: 50; margin-bottom: 5%">
      {% block content %}
      {% endblock %}
  </div>
  <footer class="mt-auto py-3" style="background-color: #272525">
    <div class="container p-4">
      <div class="row">
        <div class="col-lg-6 col-md-12 mb-4">
          <h5 class="mb-3" style="letter-spacing: 2px; color: white;">СушиЛавка</h5>
          <p style="color: white">
            Мы создаем наши блюда с любовью и страстью к кулинарии. Позвольте нам порадовать вас удивительным вкусом в каждом кусочке. Закажите прямо сейчас и наслаждайтесь нашими угощениями!
           </p>
        </div>
        <div class="col-lg-3 col-md-6 mb-4">
          <h5 class="mb-3" style="letter-spacing: 2px; color: white;">Ссылки</h5>
          <ul class="list-unstyled mb-0">
            <li class="mb-1">
              <a href="/" style="color: white;">Меню</a>
            </li>
            <li class="mb-1">
                <a href="{% url 'info:map' %}" style="color: white;">Контакты</a>
            </li>
            <li>
                <a href="{% url 'coupons:list' %}" style="color: white;">Акции</a>
              </li>
            <li class="mb-1">
              <a href="{% url 'info:info' %}" style="color: white;">О нас</a>
            </li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-6 mb-4">
          <h5 class="mb-1" style="letter-spacing: 2px; color: white;">Часы работы</h5>
          <table class="table" style="color: white; border-color: #666;">
            <tbody>
              <tr>
                <td>Пн - Пт:</td>
                <td>8:00 - 23:00</td>
              </tr>
              <tr>
                <td>Сб - Вс:</td>
                <td>9:00 - 21:00</td>
              </tr>
            </tbody>
          </table>
          <h5 class="mb-1" style="letter-spacing: 2px; color: white;">Адрес</h5>
          <table class="table" style="color: white; border-color: #666;">
            <tbody>
                <tr>
                  <td>Ипподромская улица, 1С</td>
                </tr>
        </table>
        </div>
      </div>
    </div>
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2); color: white">
      © 2023 Copyright:
      <a class="text-dark" href="https://mdbootstrap.com/">SushiLavka.com</a>
    </div>
  </footer>
  </body>
  <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
  <script>
    let blocks = document.querySelectorAll(".hide");

    blocks.forEach(block => {
        const categoryName = block.getAttribute("data-category-name");
        const span = document.createElement("SPAN");
        const text = document.createTextNode(categoryName);
        span.appendChild(text);
        span.classList.add('category-name-span');
        block.appendChild(span);

        block.addEventListener("mouseover", (event) => {
            span.style.display = "inline"; 
        });

        block.addEventListener("mouseout", (event) => {
            span.style.display = "none"; 
        });
    }); </script>
  {% block js %}
  
  {% endblock %}
</html>